spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lms_cied
    username: root
    password: root

  mvc:
    view:
      prefix: /views/
      suffix: .jsp

application:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 10